openapi: 3.0.0
info:
  title: webstoreapi
  version: '1.0'
  contact:
    name: Tobi TÃ¶gel
    email: tobias.toegel@gmx.de
  description: API for webstore application as part of the mobile applications course.
servers:
  - url: 'https://mobileappapiwebstore.herokuapp.com/'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User:
                  value:
                    username: testest
                    password: testest
                    email: testest@example.com
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      security:
        - httpBasic: []
  /register:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - username
                - email
                - password
            examples:
              Create User Bob Fellow:
                value:
                  username: fellowbob
                  password: bobfellow
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
    parameters: []
  /login:
    post:
      summary: ''
      operationId: post-login
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
      description: Post the user login information to server to check if user is authorized to login.
      security:
        - httpBasic: []
  /items:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/item'
              examples:
                example-1:
                  value:
                    id: 907bdaae-525a-41d2-9861-eb9c6b48300e
                    userId: '3'
                    title: test title
                    category: test
                    images: 'https://res.cloudinary.com/tobitgl/image/upload/v1614186732/5bc916ecf810ec3fba58a63d528a3766.png'
                    price: '200'
                    date: '2020-01-25T00:00:00'
                    deliveryType: test type
                    sellerUsername: test username
                    sellerContact: test contact
                    location: test location
            application/xml:
              schema:
                type: object
                properties: {}
        '400':
          description: Bad Request
      operationId: get-store-item
      description: Get information of items that are being sold on the webstore
      parameters:
        - schema:
            type: string
          in: query
          name: category
          description: Search and list according to category given by user
        - schema:
            type: string
          in: query
          name: location
          description: Search and list according to location given by user
        - schema:
            type: string
          in: query
          name: date of posting
          description: Search and list according to Date of posting given by user
    post:
      summary: ''
      operationId: post-store-item
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request (missing information?)
          headers: {}
        '401':
          description: Unauthorized
      description: Create new item to sell in the webstore.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/item'
          application/xml:
            schema:
              $ref: '#/components/schemas/item'
      security:
        - jwt: []
    parameters: []
  '/items/{itemId}':
    parameters:
      - schema:
          type: string
        name: itemId
        in: path
        required: true
        description: Id of an existing item.
    delete:
      summary: ''
      operationId: delete-items-itemId
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      description: Delete item from Webstore
      security:
        - httpBasic: []
    put:
      summary: ''
      operationId: put-items-itemId
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/item'
      description: Edit existing item in Webstore
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/item'
      security:
        - jwt: []
    get:
      summary: Get single Item
      operationId: get-items-itemId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/item'
              examples:
                example posting:
                  value:
                    id: 907bdaae-525a-41d2-9861-eb9c6b48300e
                    userId: '3'
                    title: test title
                    category: test
                    images: 'https://res.cloudinary.com/tobitgl/image/upload/v1614186732/5bc916ecf810ec3fba58a63d528a3766.png'
                    price: '200'
                    date: '2020-01-25T00:00:00'
                    deliveryType: test type
                    sellerUsername: test username
                    sellerContact: test contact
                    location: test location
      parameters: []
      description: Get single item
  /loginForJWT:
    get:
      summary: 'Login an get Json webtoken as a response needed for e.g. posting, deleting postings'
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  token:
                    type: string
                    minLength: 1
                    example: '"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6InRlc3RlckBtYWlsLmNvbSJ9LCJpYXQiOjE2MTQ1ODQ0MzgsImV4cCI6MTYxNDY3MDgzOH0.bw-TzZRBidMUtDeCNo67zWMpuUk2ZsFoCDlfuSGcA1g"'
                required:
                  - token
              examples:
                example token:
                  value:
                    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6InRlc3RlckBtYWlsLmNvbSJ9LCJpYXQiOjE2MTQ1ODQ0MzgsImV4cCI6MTYxNDY3MDgzOH0.bw-TzZRBidMUtDeCNo67zWMpuUk2ZsFoCDlfuSGcA1g"
            application/xml:
              schema:
                type: object
                properties: {}
        '401':
          description: Unauthorized
      operationId: get-loginForJWT
      security:
        - httpBasic: []
      description: 'Login an get Json webtoken as a response needed for e.g. posting, deleting postings'
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        userName:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - id
        - userName
        - email
    item:
      title: item
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        category:
          type: string
        images:
          type: string
        price:
          type: number
        date:
          type: string
        delivery type:
          type: string
        seller username:
          type: string
        seller contact:
          type: string
        location:
          type: string
      required:
        - id
        - title
        - category
        - images
        - price
        - date
        - delivery type
        - seller username
        - seller contact
        - location
      description: ''
  securitySchemes:
    httpBasic:
      type: http
      scheme: basic
    jwt:
      type: http
      scheme: bearer
